### ISSUE TITLE
FR: Add SBS Basestation (dump1090) Networked ADSB Support

### ISSUE THREAD

**Issue by wx4cb** [stronnag/mwptools#114]
how easy would it be to incorporate SBS messages ? this would be helpful because then you can use anything online that has an SBS format output so that you don't actually need to have an ADSB receiver. You can even use dump1090 to pull it in from any ADSB receiver or even an SDR

http://woodair.net/sbs/article/barebones42_socket_data.htm

I propose a URI something like SBS://<ip address>:30003 that way it'll identify the format and also the ip/port... 30003 is the default port for SBS on dump1090 and other software

**Comment by wx4cb** [comment]
[dump1090_sbs.csv](https://github.com/stronnag/mwptools/files/7850298/dump1090_sbs.csv)

**Comment by stronnag** [comment]
OK, I'll do it.

**Comment by stronnag** [comment]
@wx4cb  Could you please record a longer log; it would be useful to have some STA stanzas when aircraft are dropped from the picture.

**Comment by wx4cb** [comment]
Sure.. ill do it when i get home

**Comment by stronnag** [comment]
![Screenshot-20220112175522-1534x905](https://user-images.githubusercontent.com/158229/149195496-a74521be-fd2b-4a40-af5a-2e39d7f6d2a6.png)

**Comment by wx4cb** [comment]
@stronnag  I just got home and are recording some logs now, but if you can find any dump1090 SBS output on the internet you can get them yourself :D 

for example:https://www.adsbhub.org/howtogetdata.php

**Comment by stronnag** [comment]
Well, if I had nothing better to do than trawl the internet for files ...

**Comment by wx4cb** [comment]
> Well, if I had nothing better to do than trawl the internet for files ...

you mean to say youtube is not your full time job? LOL

**Comment by wx4cb** [comment]
[dump1090_sbs.csv](https://github.com/stronnag/mwptools/files/7857144/dump1090_sbs.csv)


This enough data? :dancing_men:

**Comment by stronnag** [comment]
Thanks. I'll see how that goes. Strangely, no STA messages. OTOH, the whole thing is a mess. Air position reports with no positions, no speed or course (so I compute that).

Anyway, initial attempt in `development` 
`--radar-device sbs://[host[:port]]`

**Comment by wx4cb** [comment]
@stronnag  that could be because right now it's just sitting on my tripod in the office with a crappy antenna.. there's a high likelihood that i'm missing packets and data

**Comment by stronnag** [comment]
* Will retry to connect to device every 60 seconds
* Replay tool `src/samples/sbs-test/sbs-player.rb`

**Comment by stronnag** [comment]
> @stronnag that could be because right now it's just sitting on my tripod in the office with a crappy antenna.. there's a high likelihood that i'm missing packets and data

More likely that these messages are only emitted by the original Basestation software; we don't need them as contacts will timeout just as PingRX and inav radar does.

**Comment by wx4cb** [comment]
[GlobsOfADSBDataForStronnag.zip](https://github.com/stronnag/mwptools/files/7871638/GlobsOfADSBDataForStronnag.zip)

Is this enough data ? :D FYI, it's worldwide data so not sure where it's coming from specifically, but this was just a 20 minute dump from adsbhub.

**Comment by stronnag** [comment]
I have enough data thanks

**Comment by wx4cb** [comment]
can confirm this appears to be working fine on a live ADSB stream

**Comment by stronnag** [comment]
Thanks for the confirmation.

**Comment by stronnag** [comment]
btw, ended up with c. 1100 targets logged in the big global file (more in total, as some had timed out).

**Comment by wx4cb** [comment]
lol... i dunno i started it, got caught up in a phone call and sat back down and was like... oh crap.... well.... :D
