### ISSUE TITLE
Get Stick/channel positions

### ISSUE THREAD

**Issue by ThomasCr** [stronnag/mwptools#121]
Hi,

it would be nice, to display the stick positions from the radio. Especially when replay blackbox log file.

Maybe it is already possible, but I could not find it?

Thanks

**Comment by stronnag** [comment]
It would be possible for (BBL) log replay. Consider it to be in the feature request queue. It would be useful for some diagnostics.

**Comment by stronnag** [comment]
Done in f2e8ce4. Requires the latest (1.0.1) [flightlog2kml](https://github.com/stronnag/bbl2kml) tools.
