### ISSUE TITLE
mwp checks inav version incorrectly for setting 'nav_rth_home_offset_distance'

### ISSUE THREAD

**Issue by snaewe** [stronnag/mwptools#124]
Only inav versions > 2.5.0 and <= 2.6.0 have this setting
    (if I read the git log correctly).

**Comment by snaewe** [comment]
Maybe something like this fixes it: #125

**Comment by stronnag** [comment]
But it't not a problem. If the setting doesn't exist, it's ignored.

**Comment by snaewe** [comment]
Ok. If you don't mind the error in the console logs, let's just forget about this.

**Comment by stronnag** [comment]
fixed in #125
