### ISSUE TITLE
Side Menu fonts increasing and increasing

### ISSUE THREAD

**Issue by xsnoopy** [stronnag/mwptools#127]
When I open mwp the fonts in the right menu start to increase and increase. I have a video showing this effect. https://youtu.be/syEXFi6hYOE 

The console output is:

[out.txt](https://github.com/stronnag/mwptools/files/9841528/out.txt)

**Comment by stronnag** [comment]
Please supply the mwp log `$HOME/mwp_stderr_YYYY-mm-dd.txt`.

**Comment by xsnoopy** [comment]
[mwp_stderr_2022-10-21.txt](https://github.com/stronnag/mwptools/files/9841574/mwp_stderr_2022-10-21.txt)

**Comment by stronnag** [comment]
If you can reproduce on a supported OS, please reopen.
