### ISSUE TITLE
Is there a possibility for this program to run on OS X?

### ISSUE THREAD

**Issue by liutairan** [stronnag/mwptools#13]
This tool looks really great, but is there a possibility to run on mac OS X or migrate it to OS X ? Thanks!

**Comment by stronnag** [comment]
Some users have had success running mwp within an Ubuntu or Fedora VM using parallels. Unfortunately, the mapping layer and its dependencies (libchamplain, clutter) are not well supported on platforms other than Linux and FreeBSD, so the chances of a native port for either Windows or OSX is currently zero.

**Comment by liutairan** [comment]
@stronnag  OK, I see. Thanks~

**Comment by stronnag** [comment]
You're welcome to start another issue if you need help in getting it to work in a VM. Showing some evidence of having read the installation notes (in the docs directory) for the chosen distribution will help!

**Comment by liutairan** [comment]
@stronnag  Thanks, I just got it work in VM. I got stuck with some error "VMware: vmw_ioctl_command error Invalid argument." but I finally solved that. It looks great!

**Comment by stronnag** [comment]
Cool. Don't hesitate to ask questions in the RCG thread so other users can benefit from the answers. Posting in RCG about any OSX specific problems / workarounds would be welcome too.

**Comment by liutairan** [comment]
Sure.
