### ISSUE TITLE
mwp saves layout , but does not load/restore it

### ISSUE THREAD

**Issue by xchetah** [stronnag/mwptools#148]
Hi,
Regarding #147 
after compiling mwp with the modifications , now it shows a dialog to enter a file name to save the layout to.
but loading/restoring the layout does not work, layout is always the same.
is there something missing in https://github.com/stronnag/mwptools/commit/6cdfbf2514603c34abb660f1fac7076c5c3bb98e ?
here is the saved layout file : 
[my_layout.txt](https://github.com/stronnag/mwptools/files/11653982/my_layout.txt)

I closed the Radio doc , the file saved correctly 
```
<item name="Radio" orientation="vertical" resize="yes" locked="no" iconified="no" closed="yes"/>
```
but it still shows in the layout.
any help is apreciated.

**Comment by stronnag** [comment]
Saving and restoring works fine for me.
At startup the defult `.layout` is _always_ loaded by design.
If you want a new default, save it as such.
