### ISSUE TITLE
mwp does not seed Osm Mapink maps.

### ISSUE THREAD

**Issue by xchetah** [stronnag/mwptools#149]
Hi 
using the latest mwptools , trying to seed the map at my location , I can seed bing maps , but for OSM Mapnik , I get errors .
the log shows : 
```
Tile failure status 403
```
any help is apreciated.

**Comment by stronnag** [comment]
Works here (OSM-Mapnik). 
```
09:42:37.694869 Tiles: 214 / Skip: 24 / DL: 24 / Err: 0
```
mwp just reports that which upstream reports ..... "HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it."
