### ISSUE TITLE
Exiting CLI Mode results in Reconnect-Loop

### ISSUE THREAD

**Issue by b14ckyy** [stronnag/mwptools#159]
When exiting CLI, MWP does a endless reconnect loop. 

- connect FC via USB Serial
- open CLI
- Close CLI Window

1. FC reboots
2. MWP reconnects automatically and shows telemetry
3. FC reboots again after a few seconds

This loop repeats endless. 

Tested on Raspberry Pi 4, Raspberry OS 12.
66b2add (master) / 2023-11-15T20:22:01+00:00

6.319.723
on Wayland

Logs with debug flags 4 and 64 active + raw serial logs.
[CLI Loop Logs.zip](https://github.com/stronnag/mwptools/files/13390851/CLI.Loop.Logs.zip)

**Comment by stronnag** [comment]
OK, making all serial opening asynchronous (for BLE) broke that.

**Comment by stronnag** [comment]
More likely just a remnant of legacy brokenness. But fixed in development. I
