### ISSUE TITLE
Survey Feature

### ISSUE THREAD

**Issue by relaxibus** [stronnag/mwptools#16]
Is there a plan to add a Survey Feature such as shown in this videos?
https://www.youtube.com/watch?v=7ltdY8yNcH4 (agriculture release system)
https://www.youtube.com/watch?v=LYtYYRE3Xec (camera trigger)
The MultiGCS Github: https://github.com/multigcs/multigcs

Here some nice ideas inputs for the GCS Tool:
https://www.youtube.com/watch?v=BKzJdF_fk0U

Important will be also a clear planning of battery swaps during the mission.

**Comment by stronnag** [comment]
Closing. This functionality is not an aim of the project, and in any case, a tool exists to generate survey / search missions for MW/ iNav, see http://www.iforce2d.net/surveyplanner/. The missions from this tool [work perfectly in mwp](https://www.rcgroups.com/forums/showpost.php?p=37066355&postcount=112).
