### ISSUE TITLE
WP Placement is active right after application start

### ISSUE THREAD

**Issue by b14ckyy** [stronnag/mwptools#160]
When MWP is started, I am able to place waypoints right away despite "Edit WPs" mode being off regarding button state. 

- Start MWP
- place a WP > does work 
- Click on "Edit WPs" once > Button does not change appearance > can't place waypoints anymore
- Click "Edit WPs" again > Button switches into editing state and can place waypoints as expected

I repeated the above steps in the last session of this log without debug-flags. Please tell me if a debug log is needed. 
[mwp_stderr_2023-11-17.txt](https://github.com/stronnag/mwptools/files/13390901/mwp_stderr_2023-11-17.txt)

66b2add (master) / 2023-11-15T20:22:01+00:00
6.319.723
on Wayland

**Comment by stronnag** [comment]
Doesn't happen here `x86_64` and `riscv64`.  

What's the output of ?
```
gsettings get org.mwptools.planner auto-wp-edit
```
If it's `true` then you'd get the behaviour described (some of which needs to be fixed).

**Comment by b14ckyy** [comment]
Indeed this is set to true. Can't remember that I changed that but might be when I played around a while ago. Will check with the fresh install we did on the client system 2 days ago if its the same behavior there as well (true by default) so I know If I have changed it on mine.

**Comment by stronnag** [comment]
The default is `false`, so if see that that behaviour it was changed manually.

fixed in development (803a919a), such that the EditWP button is disabled if ` auto-wp-edit` is `true`. 
Really it's an old legacy thing that I would remove ...

**Comment by b14ckyy** [comment]
Sounds good to me. The button was a bit confusing in this case but makes sense now. Think I can close here in this case.
