### ISSUE TITLE
Current and mAh not shown in Battery Monitor

### ISSUE THREAD

**Issue by cptX** [stronnag/mwptools#164]
Hi, I just installed mwp and doing some initial tests on my desk.

Although, my telemetry (ELRS running Crossfire protocol) successfully transmits the battery percentage and the current draw the Battery monitor in mwp shows only the voltage, the current is always 0.00A and the mAh are not shown at all!

I have a jumper T16 Pro and mwp connected through USB VCP.

My mwp version is 7b357534 (master) / 2023-12-24T20:26:35+00:00 6.358.735

![image](https://github.com/stronnag/mwptools/assets/9040042/0c23fd73-9875-4600-8710-63fa8f98cd2d)

**Comment by stronnag** [comment]
Works just fine here
![image](https://github.com/stronnag/mwptools/assets/158229/416d5c62-92a0-43e0-ad83-f98f85e47494)

If you provide a capture of the CRSF which exhibits this behaviour, it can be investigated further.
e.g. `mwp --raw-log`

**Comment by cptX** [comment]
Hi @stronnag, please don't close the issues so fast, before even investigating if there is really a bug. Also, it's not very polite for the person that spent time reporting it. Personally, it pissed me off to be honest. I'll try to provide the logs.

**Comment by stronnag** [comment]
The [User Guide](https://www.daria.co.uk/mwptools/mwp_support/) makes it quite clear that Issues that do not supply required / mandatory information may be closed immediately. 
I do not have time to waste with people who cannot be bothered to help me to help them.
