### ISSUE TITLE
LoS analysis does not seem to work

### ISSUE THREAD

**Issue by tomaskir** [stronnag/mwptools#167]
LoS Analysis seems to do nothing for me.

Here is how it looks like for me with a random mission for showcase purposes:
![Peek 2024-02-05 12-31](https://github.com/stronnag/mwptools/assets/8025781/924e9e70-7166-4188-bc12-ea6b7b942d4a)

This is on the new `7.028.536` just built from AUR. This should draw LoS lines on the map, right?

**Comment by stronnag** [comment]
Please post the log are described in  the [user guide](https://www.daria.co.uk/mwptools/mwp_support/#support)

**Comment by stronnag** [comment]
And the random mission file ...
