### ISSUE TITLE
Confusing Installation Instructions for mwptools on Windows 11 WSL using Ubuntu 22 .04.3

### ISSUE THREAD

**Issue by packetkiller** [stronnag/mwptools#173]
Attempted to install using latest instructions here: https://www.daria.co.uk/mwptools/mwp-in-Windows-11---WSL-G/
Got mixed result of some things downloaded and installed and others had install issues or just did not seem to work.
I have meticulously documented my steps but have had to go back and fourth with several of the suggestions found mixed into the instructions above, for how to get around issues...so my steps are a mess and I have yet to be successful.

First time seeing mwptools so I am probably just hacking up the instructions. You have some awesome stuff here...but I am having trouble following what you have been successful and use as official instructions and what may be old articles and steps that may be causing me to screw up the deployment.

1) Please help me understand what and where the latest and proper instructions are that I should be following for a mwptools on Windows 11 host using WSL Ubuntu 22.04.3 image to host mwptools.
2) I would be happy to assist with any English install instruction updates if that would help you out, assuming I am deemed worthy. I get what is being attempted and I understand many of the images and dependencies have recently been changing, so I am assuming this install issue is something I am doing out of order, but I am guessing the instructions may also be lagging a bit, and so I am offering to help maintain. I am also assuming mwptools works just fine.

If I should be making this request and asking questions in another location / preferred location, please just tell me where and we can close this issue and I will open a new question where you specify.

Here is what I attempted:
To install on Windows 11 using WSL Ubuntu 22.04.03:
1)	Install the Windows feature Windows Subsystem for Linux (WSL)
2)	Install all patches
3)	Run the WSL update (wsl_update_x64.msi)
4)	Go to Windows Store and install (Get) Ubuntu (I used Ubuntu 22.04.3 LTS)
5)	Once Ubuntu and the wsl update is installed, select “Open” on the Ubuntu Windows Store application
6)	Add a user name and password at the Ubuntu operating system logon prompt (ex: root = somepassword, user1 = somepassword)
7)	Logon as user1
8)	Check for Ubuntu updates:
        sudo apt update
        Patch Ubuntu:
	sudo apt upgrade
9)	Make new Projects folder in home directory: /home/user1/Projects
10)	Move install script to /home/user1
	deb-install.sh
11)	Make shell script executable
	sudo chmod +x deb-install.sh
12)	In the Windows Terminal change to the Projects directory
	cd /home/user1/Projects
13)	Clone mwptools repo: git clone https://github.com/stronnag/mwptools.git
14)	Change to the users’ home path root folder
	cd /home/user1
15)	Execute the script:
	./deb-install.sh -y
16)	Executables are in ~/.local/bin

Things did not work but no errors on the install and no icons were showing where the instructions stated they should be...I am assuming I just hacked up the install at this point...or should be doing additional steps...it became unclear when following the documentation
No errors. Installed dependencies and such and made the install folders...just seem to be missing something to get mwp to start/work.  Am I missing a compile or something? Did I even come close to executing the correct steps to install?

Tried to add these things...did not help:
17)	sudo apt install adwaita-icon-theme-full
18)	# updated in /etc/hosts for ipv6
        ::1   localhost ip6-localhost ip6-loopback
19)	### Add the following entry to /etc/wsl.conf:
        [network]
generateHosts = false
20)	gsettings set org.mwptools.planner font-fv 10
# if you still have resizing problems, try 9
21)	sudo apt install evolution -Y
22)	GDK_BACKEND=x11 evolution

Tried this also...seemed to be some other instructions for how to do the same install but still did not work:	
25)	curl -LO https://github.com/stronnag/mwptools/releases/download/7.111.629/mwptools_7.111.629_amd64.deb
sudo apt install ./mwptools_7.111.629_amd64.deb

No errors. Installed dependencies and such and made the install folders...just seem to be missing something to get mwp to work. Sort of the same issue I ran into above. Am I missing a compile or something?

Never got this far but did check and did not see if these icons and such showed up...they did not:
30)	After install and compile completes, you should see new icons for “MWP Area Planner (Ubuntu-22.04)” and “MultiWii Planner (Ubuntu-22.04)” in the start menu
31)	cd mwptools/src/samples/s2n
32)	sudo make ser2udp.exe
33)	Go to windows explorer and navigate to /Ubuntu-22.04/home/pblake-adm/mwp/mwptools/src/samples/s2n and locate the ser2udp.exe file. Copy the file to D:\Install Media\mwptools directory
34)	To get mwptools to connect to a flight controller (FC), add to device list in the menu item in “MultiWii Planner (Ubuntu-22.04)”. Select menu item Edit\Preferences, then go to the Device List item. Enter udp://__MWP_SERIAL_HOST:17071
35)	Select the above device from the device option drop down menu item
36)	Go to the Windows Firewall settings and add the ser2udp.exe application, allowing all networks (even private and public)

Appreciate all the cool work you put into this...

**Comment by stronnag** [comment]
Issues are for problems, not a personal blog. If you have a problem, please state what it is. 
Please also do not claim that the documentation says things that it does not. 

If you have a specific issue, please state it honestly and the issue can be reopened.
Please also note that WSL is not a supported environment.
