### ISSUE TITLE
Zoom out after WP edit

### ISSUE THREAD

**Issue by Scavanger** [stronnag/mwptools#181]
After editing a waypoint and clicking on apply, the system zooms out. In other words, the entire world map is displayed.

**Comment by stronnag** [comment]
Version ?
Operating System?

**Comment by stronnag** [comment]
And the mwp_stderr_yyyy_mm_dd log please.

**Comment by stronnag** [comment]
Never mind. I can reproduce that ...

**Comment by stronnag** [comment]
Fixed in development branch (unless you have some cunning way of making it happen that I don't know off)
