### ISSUE TITLE
[Windows] MWP freezes when LOS analysis done over slow Serial link (BT/mLRS)

### ISSUE THREAD

**Issue by b14ckyy** [stronnag/mwptools#185]
Steps to reproduce: 

- Conenct to a FC over a wireless link (mLRS via BT-SPP in our case but probably another SiK or BT Link will work too)
- Wait for poller to start
- Create a simple WP mission or download from FC, does not matter
- Start LOS analysis
- Watch a popup with Telemetry stall for 5s appears (shows over USB-VCP as well)
Result: As soon as LOS analysis is complete, the application freezes and has to be force closed. 

Log from me: [mwp_stderr_2024-12-18.txt](https://github.com/user-attachments/files/18181309/mwp_stderr_2024-12-18.txt)
Log from user with debug-flags 512: 
[mwp_stderr_2024-12-18 (1).txt](https://github.com/user-attachments/files/18181368/mwp_stderr_2024-12-18.1.txt)

![image](https://github.com/user-attachments/assets/c1076369-b3e2-40bb-a38b-9283168344db)

Additional Info: 
- issue does not happen if FC is connected via VCP
- Telemetry polling continues after MWP Interface is frozen, as I can see mLRS is still in GCS-Polling mode that parses only messages requested by the GCS over Serial. This results in a Slow 1Hz telemetry update rate and shows that MWP is still communicating with the FC. 
- gdbus.exe stays open and has to be terminated before MWP can be launched again

**Comment by stronnag** [comment]
Cannot reproduce
CC2541 BLE slow as anything
```
13:27:15.076383 156.192s, rx 4744b, tx 2158b, (30b/s, 14b/s) to 3 wait 0, avg poll loop 1796 ms messages 209 msg/s 1.3
```
(1.3. MSP / second).
LOS works just fine. (Arch Linux).

**Comment by stronnag** [comment]
But good .... No weird stuff
```
2024-12-18T09:12:01-0300 Locale: es-AR (-34.736 -58.656 / -34,736 -58,656)
```

**Comment by stronnag** [comment]
Can't reproduce (easily) in Windows either.
```
13:49:10.756139 Arming flags: Navigation unsafe, • Fix quality, • 0 satellites,RC Link (40800), load 10% MSP_CMDS_INAV_STATUS
13:49:10.756139 Sensors: Acc Baro GPS  (008b)
13:49:10.756139 INAV v8.0.0  WINGFC (253cf74b) «BENCHYMCTESTY»
13:49:10.756139 Poller cycle for  9 items, 81 / 226 bytes (INAV_STATUS,ANALOG2,NAV_STATUS,RAW_GPS,COMP_GPS,GPSSTATISTICS,WP,ATTITUDE,ALTITUDE)
13:49:10.756139 Start poller
13:50:20.402154 MSP Timeout 793 756 756 (MSP_CMDS_INAV_STATUS MWP_SERSTATE_POLLER)
13:50:36.194300 MSP Timeout 920 883 883 (MSP_CMDS_COMP_GPS MWP_SERSTATE_POLLER)
13:51:00.710757 MSP Timeout 1128 1091 1091 (MSP_CMDS_INAV_STATUS MWP_SERSTATE_POLLER)
13:51:01.132856 Comms error Mav/CRC 1
13:51:04.772938 MSP Timeout 1165 1128 1091 (MSP_CMDS_INAV_STATUS MWP_SERSTATE_POLLER)
13:52:04.218617 Serial closed replay 0
13:52:04.218617 197.097s, rx 5652b, tx 2405b, (29b/s, 12b/s) to 6 wait 0, avg poll loop 1387 ms messages 238 msg/s 1.2
13:52:04.218617 :DBG: Close for socket closed=false
13:52:04.219645 :DBG: clearup closing 2
13:52:04.219645 :DBG: clearup closing 3
13:52:04.219645 :DBG: Close I/O thread
```

Some timeouts, but there's just 2 CPUs in the VM. Serial recovers 1.2 MSP/sec). How slow do you need?
CC2541 again over TCP bridge.

**Comment by b14ckyy** [comment]
OK so speed does not seem to be the relevant factor here in this case. 
Running over mLRS in 31Hz mode allows full 1Hz telemetry updates. so its significantly faster than 1.2MSP/s 

I could run a serial log if that helps?

**Comment by stronnag** [comment]
Windows again, ancient E45-TTL-100 LoRa, 9600 baud everywhere. I can pass through the ground side USB) to the Windows VM, so it's going through the serial reader (rather than IP). Not much faster, some timeouts during the LOS (otoh, the two CPU VM is probably starving the serial I/O thread).  But it works just fine.
```
14:25:34.705404 Trying OS open for COM7@9600 \Device\Silabser0
14:25:34.785010 Connected COM7@9600 \Device\Silabser0 (nopoll false)
14:25:34.785994 :DBG: Open I/O thread
14:25:34.953421 Msp Error: MSP_CMDS_IDENT[0x64,100,0b]
14:25:35.125700 Using Msp v2 0205
14:25:35.375486 Model name: "BENCHYMCTESTY"
14:25:35.609802 V2 mixer 8 1
14:25:36.328338 Feature Mask [10480cd6] : telemetry true, gps true, current true
14:25:37.062604 INAV v8.0.0  WINGFC (253cf74b)
14:25:37.937592 Initial cycle 3.156197 (b=400 r=126.7, bi=1013.9) *
14:25:37.937592 Boxids: [ 0 51 61 1 2 35 5 8 11 49 10 28 53 45 30 31 55 59 56 3 12 36 37 21 54 64 13 60 19 26 27 39 40 41 42 43 44 62 63 65 66 67]
14:25:37.937592 Masks arm=1 angle=8 horz=10 ph=100 rth=400 wp=800 crz=2000 fs=40000000
14:25:38.266036 WP_GETINFO: 120/0/0
14:25:38.820042 Activeboxes 8 40100000 00000000
14:25:38.820042 Requesting common settings
14:25:38.820042 Request setting nav_wp_max_safe_distance
14:25:38.820042 Request setting inav_max_eph_epv
14:25:38.821044 Request setting gps_min_sats
14:25:38.821044 Request setting safehome_max_distance
14:25:38.821044 Request setting nav_fw_land_approach_length
14:25:38.821044 Request setting nav_fw_loiter_radius
14:25:39.259667 Received nav_wp_max_safe_distance: 20000m
14:25:39.932578 Received inav_max_eph_epv: 1000
14:25:40.550022 Received gps_min_sats: 6
14:25:41.019226 Received safehome_max_distance: 100m
14:25:42.019269 Received nav_fw_land_approach_length: 350m
14:25:42.787487 Received nav_fw_loiter_radius: 75m
14:25:43.070979 Arming flags: Navigation unsafe, • Fix quality, • 0 satellites,RC Link (40800), load 10% MSP_CMDS_INAV_STATUS
14:25:43.070979 Sensors: Acc Baro GPS  (008b)
14:25:43.070979 INAV v8.0.0  WINGFC (253cf74b) «BENCHYMCTESTY»
14:25:43.070979 Poller cycle for  9 items, 81 / 226 bytes (INAV_STATUS,ANALOG2,NAV_STATUS,RAW_GPS,COMP_GPS,GPSSTATISTICS,WP,ATTITUDE,ALTITUDE)
14:25:43.070979 Start poller
14:26:11.176977 MSP Timeout 283 246 246 (MSP_CMDS_WP MWP_SERSTATE_POLLER)
14:26:19.383149 MSP Timeout 351 314 314 (MSP_CMDS_COMP_GPS MWP_SERSTATE_POLLER)
14:26:23.468842 MSP Timeout 388 351 314 (MSP_CMDS_COMP_GPS MWP_SERSTATE_POLLER)
14:26:24.442497 Serial closed replay 0
14:26:24.442497 49.346s, rx 1987b, tx 938b, (40b/s, 19b/s) to 3 wait 0, avg poll loop 1178 ms messages 86 msg/s 1.7
14:26:24.443495 :DBG: clearup closing 2
14:26:24.443495 :DBG: clearup closing 3
14:26:24.443495 :DBG: Close I/O thread
14:26:26.647630 Terminated bproxy
14:26:26.647630 Cleaning up ...
```
Magnificent 1.7 MSP /sec.
![image](https://github.com/user-attachments/assets/ad32cee1-f1d5-4a59-a7df-f87ac60d023d)

**Comment by stronnag** [comment]
> OK so speed does not seem to be the relevant factor here in this case. Running over mLRS in 31Hz mode allows full 1Hz telemetry updates. so its significantly faster than 1.2MSP/s
> 
> I could run a serial log if that helps?

Can you try the attached with  `--debug-flags 512` please.
[mwp-exe-2024-12-18a.zip](https://github.com/user-attachments/files/18184179/mwp-exe-2024-12-18a.zip)
And let me have the log.

**Comment by b14ckyy** [comment]
Done. I have not deleted the old log so its just the last session. 

[mwp_stderr_2024-12-18.txt](https://github.com/user-attachments/files/18184950/mwp_stderr_2024-12-18.txt)

One additional note: When the freeze happens, sometimes it does react for a fraction of a second and updates the UI and freezes again. It reacted maybe 1-2 times per minute but it was not regular. CPU load was close to 0%.

**Comment by stronnag** [comment]
So I have no way to reproduce this so let's disable analytical stuff while there is an active serial port on Windows.

**Comment by b14ckyy** [comment]
I suggest to put out a warning popup that its not recommended to use if a connection over serial is active. 
if you say over multiple other connection type it works for you and only for one user and me it breaks with mLRS in both cases, maybe its something specific to that link.

**Comment by stronnag** [comment]
It's done. Disable on Windows when connected. Simple, unambiguous. It will be documented under Windows restrictions (when I get around to writing the Windows specific part of the documentation).

I never really envisioned terrain / LOS analysis as anything other than an offline activity anyway,

**Comment by stronnag** [comment]
"Fixed" (or at least avoided) in development branch d2d9781f17db833566ee19370bd951bca63040c0
