### ISSUE TITLE
mwp should have a pause button during blackbox replay

### ISSUE THREAD

**Issue by giacomo892** [stronnag/mwptools#21]
As for the title.

**Comment by stronnag** [comment]
Indeed it should, this is not the first suggestion. Unfortunately as the replay is provided by a separate process, it's non-trivial to solve. We shall see, thanks for raising the issue.

**Comment by stronnag** [comment]
Initial cut at this in 6d52e7473fe9f67b5ed79f073e56f7d5d8a375ee. Pressing <SPACE> during replay will pause / resume the replay,

**Comment by giacomo892** [comment]
tested and it works.

**Comment by stronnag** [comment]
Congratulations on upgrading to a modern distro.

**Comment by giacomo892** [comment]
I've only tried it on VM 🍡 💃 👯

**Comment by stronnag** [comment]
Closing as implemented and tested

**Comment by giacomo892** [comment]
Maybe also adding a pause button is not a totally bad idea :)

**Comment by stronnag** [comment]
If the main aim of the application was to replay log perhaps. 
But it's just a side effect.

**Comment by giacomo892** [comment]
Is your mainly usage to upload missions and monitor them in real time?

**Comment by stronnag** [comment]
The clue's in the name, so yes planning and monitoring; mwp log replay was late in the game, blackbox replay more so. Not to say they are not useful functions (probably more so than I expected), but not the main aim.
