### ISSUE TITLE
Replay fast forward

### ISSUE THREAD

**Issue by giacomo892** [stronnag/mwptools#22]
Is it possible to implement it?

**Comment by stronnag** [comment]
Some how I knew that was coming next :)

There is a load command that loads the whole file quickly, full VCR type controls are rather more difficult and less likely to happen.

**Comment by giacomo892** [comment]
Ok. I'll read the documentation.

**Comment by stronnag** [comment]
It's on the File menu (Replay X, Load X) Load does it about as fast as the UI can keep up.

**Comment by stronnag** [comment]
closing, because I'm not currently bored enough to implement an VCR style forward / back / fast / slow control.
