### ISSUE TITLE
mwp crashes on raspian / RPI 3 : Review Voice API choices

### ISSUE THREAD

**Issue by stronnag** [stronnag/mwptools#27]
As https://www.rcgroups.com/forums/showpost.php?p=38601807&postcount=197

mwp:1279): Gtk-WARNING **: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
pi@raspberrypi:~/.config/mwp $ mwp
2017-11-09T04:13:16+0000 mwp startup version: mwp df508c1 / 2017-11-09 0.312.788
2017-11-09T04:13:16+0000 default options: --rings 10,20 -S 64 

** (mwp:1443): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
2017-11-09T04:13:17+0000 Using speech api 2 [speechd]
2017-11-09T04:13:18+0000 libchamplain 0.12.15

(mwp:1443): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)

(mwp:1443): Gtk-WARNING **: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node block, owner GtkLevelBar)
Segmentation fault

**Comment by stronnag** [comment]
I'm not sure this is audio related; it could be almost anything in startup. I'll see what happens in a 'Stretch' VM (intel to start with).

**Comment by stronnag** [comment]
I just installed a kvm/qemu stretch amd64 VM, choosing xfce as the desktop. Installed the dependencies, `make && sudo make install`. Result: a working mwp. Add Debian (on amd64) to the list of supported OS.

Unfortunately, this helps you not one iota. I no longer have a Pi (my < 10,000 serial no version 1 died recently). Let me contemplate a rapsian VM (at least if it rains over the weekend).

**Comment by markandkymward** [comment]
This fault is repeatable whenever you select the audio click box. I’d be glad to run scenarios to help with this. I’m excited about adding this functionality to my ground station plan.

**Comment by stronnag** [comment]
Does not happen in my Stretch VM, so I guess it's raspian based. You could try the alternative speech api.
````
apt-get install libspeechd-dev # if not already installed
gsettings set org.mwptools.planner speech-api  speechd
````

**Comment by stronnag** [comment]
You could also replace `espeak` with the newer `espeak-ng`. mwp doesn't care, as they're api compatible
````
sudo apt-get install libespeak-ng-libespeak-dev libespeak-ng-dev espeak-ng
````

**Comment by markandkymward** [comment]
espeak from the command line works as advertised.  I get the requisite ¨hello¨ verbal from the audio jack. I noticed that mwp tries to load speechd even affter I attempt to change speech-api gsettings using:


 pi@raspberrypi:~/git/mwptools/common $ sudo gsettings set org.mwptools.planner speech-api espeak
pi@raspberrypi:~/git/mwptools/common $ mwp
2017-11-09T20:58:40-0500 mwp startup version: mwp df508c1 / 2017-11-09 0.312.788
2017-11-09T20:58:40-0500 default options: --rings 10,20 -S 64 --centre 41.2141,-73.0502 --serial-device /dev/ttyUSB0@19200 --connect --speech-api espeak 

** (mwp:2227): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
2017-11-09T20:58:41-0500 Using speech api 2 [speechd]
2017-11-09T20:58:42-0500 libchamplain 0.12.15

**Comment by markandkymward** [comment]
not sure why those lines are lined out, artefact of copy-paste my guess.

**Comment by markandkymward** [comment]
Solved it, at least partially.  I did a sudo apt-get purge libspeechd-dev then rebuilt mwp with make && make install.  It now loads espeak on start-up and functions as expected.  I am perfectly happy with the default espeak voice, albeit a wee bit ¨British" for my taste ;).  Seems raspian (stretch) has issue with speechd when it picks it up con compilation.  This is very exciting for me because I can now build in a computer terminal into my ground station in case I need it in the field and I no longer have to lug a separate laptop.  For what it is worth, mwp runs fine on the Pi3 with stretch.  Maps load a tad slow but once loaded it appears to be fine.  I set my GPU memory split at 128.  I just need to find a larger screen that runs on 12 volt/RCA input now.

**Comment by stronnag** [comment]
Few  things:
* You should run `gsettings` as the local user, not sudo / root
* I will check that `speech-api` CLI over-ride still works
* You can change the `espeak` voice.
````
gsettings set org.mwptools.planner espeak-voice 'en' # the default
# list all espeak voices
espeak --voices
gsettings set org.mwptools.planner espeak-voice 'en-us' # any different?
# list all gsettings (also in the mwp manual)
gsettings list-recursively org.mwptools.planner 
````
And there is a graphical `dconf-editor` tool to edit gsettings as well.
Anyway, glad it's working.

**Comment by markandkymward** [comment]
Just kidding on the voice - I actually kind of like it.  Thanks for the clarity on gsettings, I'll dig some more  on my own.   I do own a license for a Cepstral voice that I've used on other projects.  Is there a way to set mwptools to this?

**Comment by stronnag** [comment]
It might be, I've just downloaded their 'millie' sample. What this space.

**Comment by stronnag** [comment]
It's not, they need to move into the 21st century.  `oss_audio: failed to open audio device /dev/dsp` --- it's not 1997 any more.

**Comment by markandkymward** [comment]
No problem.  Stephen Hawking it is.  Adds a touch of class rather than some fake Yank's voice.  Thanks again.

**Comment by stronnag** [comment]
I think we're done on this one, closing.

**Comment by stronnag** [comment]
@markandkymward 

It's a cold and windy day here, so let's reinstate the old, undocumented external voice API (which should allow you to use the Cepstral voice), thusly:
````
git pull
git checkout external_voice_api
git pull # for good measure
make && sudo make install
# Need to set the MWP_SPEAKER environment variable. This can be made permanent in 
# .bashrc, .bash_profile or .pam_environment, for now we just set in for command invocation, e.g.
#  MWP_SPEAKER=speak mwp # for espeak (pointless, as the internal api is more efficient)
#  MWP_SPEAKER="spd-say -e" mwp # for speech-dispatcher (pointless, as the internal api is more efficient)
# Cepstral, note "-f -" required for pipe/stdin, ensure "swift" is on the PATH, or add explicit path
# Add any other parameters (e.g. the voice name) 
#
MWP_SPEAKER="swift -f -" mwp  
````
Let me know if / how well it works, and I'll merge it into master.

**Comment by stronnag** [comment]
Only now it uses a command option rather than a environment variable (and may even work with the gratuitously non-interoperable  Cepstral api).
````
mwp --voice-command  "spd-say -t female2 -e"
````
Substitute your preferred command.

**Comment by markandkymward** [comment]
worked like a champ with cepstral.

**Comment by stronnag** [comment]
merged
