### ISSUE TITLE
Unexpected removal of .layout.xml breaks the dock

### ISSUE THREAD

**Issue by stronnag** [stronnag/mwptools#28]
Via user Alle_Ita on RCG https://www.rcgroups.com/forums/showpost.php?p=38633222&postcount=212

**Comment by stronnag** [comment]
This may take a while ....

**Comment by stronnag** [comment]
OK, so lets start be seeing what's happening in the configuration directory. Please post the output of:
````
ls -lR ~/.config/mwp
````

**Comment by AlleIta** [comment]
Here the output:
/home/alle/.config/mwp:
totale 4
-rw-rw-r-- 1 alle alle 437 nov  7 15:43 sources.json

**Comment by stronnag** [comment]
Sorry, my mistake:
````
ls -lRa ~/.config/mwp

````

**Comment by AlleIta** [comment]
/home/alle/.config/mwp:
totale 16
drwxrwxr-x  2 alle alle 4096 nov 14 22:08 .
drwx------ 18 alle alle 4096 nov  7 15:51 ..
-rw-rw-r--  1 alle alle   37 nov 14 22:08 .layout.xml
-rw-rw-r--  1 alle alle  437 nov  7 15:43 sources.json

**Comment by stronnag** [comment]
Good. `.layout.xml` should be much bigger, like about 3kB. Can you attach it please.

**Comment by AlleIta** [comment]
I changed the extension to .txt otherwise it is not possible to attach the file.
Please remove the .txt
[.layout.xml.txt](https://github.com/stronnag/mwptools/files/1472611/default.layout.xml.txt)

**Comment by stronnag** [comment]
Thanks. This is a puzzle, more tomorrow.

**Comment by stronnag** [comment]
So. if I remove my .layout.xml and use yours (which contains no data), I get:
````
2017-11-14T21:46:56+0000 Removing /home/jrh/.config/mwp/.layout.xml 0
````
as expected, and then this:
![screenshot-20171114214733-1300x846](https://user-images.githubusercontent.com/158229/32807053-9fbab3c2-c986-11e7-975d-3ea1cdce7cf1.png)

All the dock icons are in the vertical bar, I can click them to open them  in the dock and close the items I don't want (so they return to the View menu). Then if I use File/Quit, the layout is saved (destroying the window does not save the layout, this is a feature).
````
$ ls -lstra ~/.config/mwp/.layout.xml ## note the file size ....
4 -rw-r--r-- 1 jrh jrh 3895 Nov 14 21:52 /home/jrh/.config/mwp/.layout.xml
````
And I have my favourite layout again.
![screenshot-20171114214938-1479x846](https://user-images.githubusercontent.com/158229/32807237-25da215e-c987-11e7-92d4-a51f40c241ab.png)

**Comment by AlleIta** [comment]
When you use my .layout.xml, does the item appear in the view menu by closing it in the dock?
Actually, if I close an item in the dock then I can not open it anymore in the view menu.
I did not tried to file/quit after closing an item in the dock....I have only tried to destroy the windows to be sure to have all the items back in the dock.

**Comment by stronnag** [comment]
Yes, it does. So why don't you try the attached [layout.xml.txt](https://github.com/stronnag/mwptools/files/1475596/layout.xml.txt)
````
cp layout.xml.txt ~/.config/mwp/.layout.xml
`````

**Comment by AlleIta** [comment]
I tried the your file attached and this is what happen.
If I launch mwp, I can see your layout and in the view menu I can see the items you disabled.
I can enable them from the view menu.
If I enable them from the view menu, as soon as I close the items they disappears and they do not appear anymore in the view menu....and I come back at my initial situation.
[.layout.xml.tar.gz](https://github.com/stronnag/mwptools/files/1476346/default.layout.xml.tar.gz)

Enclosed you can find the .layout.xml after disabling the battery monitor and File->quit.

**Comment by AlleIta** [comment]
I did other tests and if I disable an item in the dock, the item does not appear in the view menu.
If I file->quit and open again mwp the item appears in the view menu.
Should it works in this way?

**Comment by stronnag** [comment]
No, your system is somewhat broken. Is it native or in a VM. Non of my machines / VMs on Arch, Fedora, FreeBSD, Ubuntu or Elementary (I thing that's the lot) behave in that way.

**Comment by AlleIta** [comment]
it is a native system. I have a double partition (windows 10 and Ubuntu 16.04 LTS).
Now if I replace the .layout.xml with my original one, I do not have anymore the:
- 2017-11-14T22:04:15+0100 Removing /home/alle/.config/mwp/.layout.xml 0
How I can fix it and let mwp behave how it should? all the dependencies are installed. I checked them and made a git pull && make && sudo make install

**Comment by stronnag** [comment]
I really have no idea. What desktop are you using ? Unity ?

**Comment by AlleIta** [comment]
The one installed with Ubuntu 16.04 LTS

alle@Portatile:~$ ls -l /usr/share/xsessions/
totale 4
-rw-r--r-- 1 root root 204 ago 22  2016 ubuntu.desktop

**Comment by stronnag** [comment]
I just changed by Ubuntu 16.04 VM from gnome to ubuntu-desktop. Makes no difference, mwp behaves as designed. I'm really out of ideas of what to try next.

**Comment by AlleIta** [comment]
Do you think that by removing completely mwptools and build and install it again from new could solve this issue? If you think that is worth a try, can you please tell me how to completely remove mwp?

**Comment by stronnag** [comment]
Not yet, I have a few things to try later.

Fyi, there is an uninstall script. I think the INSTALL file describes where it is, samples maybe.

**Comment by AlleIta** [comment]
OK, waiting for the next things to try.

**Comment by stronnag** [comment]
OK, first how it works at the moment. mwp is set up so that when you open the 'View' menu, the application is signalled and sets the dock items' status. This appears to work for every mwp user on multiple OS, apart from you for some reason.

So please do the following:
````
git pull
git checkout gdl-test
git pull # probably not necessary ....
make && sudo make install
````
Then run mwp from a terminal (if necessary please use my `.layout` from yesterday) so there is a mixture of open / icon / closed dock items. Don't change the dock, just open the View menu. Then quit mwp and send me the terminal log. It should look like:
````
$ mwp
2017-11-16T17:14:05+0000 mwp startup version: mwp local / 2017-11-16 0.320.620
2017-11-16T17:14:05+0000 default options: --rings 50,20
2017-11-16T17:14:05+0000 Using speech api 1 [espeak]
2017-11-16T17:14:05+0000 libchamplain 0.12.16
2017-11-16T17:14:05+0000 Starting external qproxy process
2017-11-16T17:14:05+0000 Starting proxy thread
2017-11-16T17:14:11+0000 setting status from menu view
````
The last line is from the View menu signal. I'd like to know if you see it.

Then please run mwp again, as below, with the `--dock-test` flag. This disables the 'View' clicked signal and instead updates the menu every time the dock changes (somewhat unnecessarily, as just moving a dock item causes the layout change event to file).

So in this second test, please:
* Close one of the dock items (the battery from my layout would be fine)
* Check the menu, if the battery item is enabled, please add it back to the dock bar and then the dock

Again, please collect the terminal log for me, and also describe what you see in the menu. The log should look something like:
````
$ mwp --dock-test
2017-11-16T17:15:03+0000 mwp startup version: mwp local / 2017-11-16 0.320.620
2017-11-16T17:15:03+0000 default options: --rings 50,20
2017-11-16T17:15:04+0000 Using speech api 1 [espeak]
2017-11-16T17:15:04+0000 libchamplain 0.12.16
2017-11-16T17:15:04+0000 Starting external qproxy process
2017-11-16T17:15:04+0000 Starting proxy thread
2017-11-16T17:15:20+0000 setting status from layout change
2017-11-16T17:15:27+0000 setting status from layout change
2017-11-16T17:15:27+0000 setting status from layout change
2017-11-16T17:15:32+0000 setting status from layout change
````

**Comment by stronnag** [comment]
OK, it's an Ubuntu bug. If you have the app menu set (one menu at the top), the menu update event is not sent. If you have normal menus (menu in the window) then it works correctly (like it does not every other OS). I'm not fixing this. You can fix Ubuntu's stupidity by adding to `/etc/environment`:
````
UBUNTU_MENUPROXY=0
````

**Comment by stronnag** [comment]
Closing this issue as it's an Ubuntu bug.

**Comment by AlleIta** [comment]
Ok. 
I do not have one menu at the top. 
I have the menu in the window and not the app menu set.
In the /etc folder I can not find any environment folder.
I tried: sudo echo "UBUNTU_MENUPROXY=0" >> /etc/environment
but I have "bash: /etc/environment: permission denied"

**Comment by stronnag** [comment]
````
sudo -i
echo "UBUNTU_MENUPROXY=0" >> /etc/environment
````

**Comment by stronnag** [comment]
Looks like a menu at the top in the screen shot

**Comment by AlleIta** [comment]
still "bash: /etc/environment: permission denied"

**Comment by AlleIta** [comment]
sorry, it was my fault.
I succed with two steps....
- sudo -i
- echo "UBUNTU_MENUPROXY=0" >> /etc/environment

When I start mwp, still the same behaviour

**Comment by stronnag** [comment]
You at least log out and log in

**Comment by AlleIta** [comment]
Ops...sorry, my second fault. I'm newbie.
I did a reboot and it works perfectly.
Thank you very much for your help and patience.
I appreciate.
Thank you again.

**Comment by stronnag** [comment]
No problem. Actually, I probably will provide a workaround.

**Comment by stronnag** [comment]
With the latest commit, you should be able to build mwp as:
````
DOPTS="-D BROKEN_MENUS" make && sudo make install   
````
and it should  work even with Ubuntu's global app menu (so you can remove `UBUNTU_MENUPROXY=0` from `/etc/environment`)

**Comment by AlleIta** [comment]
OK....super!
Thank you

**Comment by stronnag** [comment]
Later, there will be a completely automatic (detected at run time) fix

**Comment by stronnag** [comment]
It's now fixed (I think). No special branches, no strange build commands.
````
git checkout master # one off, just in case
git pull && make && sudo make install
````

**Comment by AlleIta** [comment]
Ok, thank you.
I will test if it works on my computer.
Can you please tell me how to delete the UBUNTU_MENUPROXY=0" in the /etc/environment?

**Comment by stronnag** [comment]
Just edit with any text editor. There's a very simple editor called nano on Ubuntu.
Remove the line, CTRL-O (^O) to save the file, CTRL-X (^X) to exit. Done.

**Comment by AlleIta** [comment]
Ok, it works great on my computer!
Thank you
