### ISSUE TITLE
Artificial horizon indicator - possible GUI enhancement

### ISSUE THREAD

**Issue by marksev1** [stronnag/mwptools#3]
I'd propose also a artificial horizon indicator as an enhancement to your gui. Like the "major" autopilot gui's have, like taulabs gcs, apm-planner etc.

Just an idea!
Have fun & great work so far!

**Comment by stronnag** [comment]
Until the new horizon stuff is fully working, let's leave this open. Currently it highly experimental and not 100% reliable.

**Comment by stronnag** [comment]
The horizon and flight view items appear stable (with good GTK themes). The issue will be closed after the documentation has been updated.

**Comment by stronnag** [comment]
Completed, apparently stable (if dock items fail to update, it's probably a bad GTK theme). Documentation updated.
