### ISSUE TITLE
Feature Request: Please make flight statistics window user configurable.

### ISSUE THREAD

**Issue by ninja-zx11** [stronnag/mwptools#45]
Please make flight statistics window user configurable so that user can add their needed values like max altitude,Max gps distance from the armed position,max amps etc.Thanks.

**Comment by stronnag** [comment]
As of 2018-07-20, the `development` branch has an expanded flight stats display. 
Max current will not be added until the 2.0 BB format is finalised and documented.

![image](https://user-images.githubusercontent.com/158229/43026158-5c6d74fc-8c6c-11e8-9c8e-ed421884c7d7.png)

**Comment by ninja-zx11** [comment]
I appreciate your work!! Thanks for your support.

**Comment by stronnag** [comment]
I now appear to understand both the old and new bbox battery stuff

![image](https://user-images.githubusercontent.com/158229/43038489-75caac6c-8d11-11e8-8543-e5fcd611a247.png)

I think this is one of yours.  Development branch as of 2018-07-21 17:10 ish.

Requires blackbox patched with `mwptools/samples/consolidated-blackbox-inav.dif`

**Comment by ninja-zx11** [comment]
This is awesome!!
So maximum range is max straight line distance from the launch location?Thanks for adding this feature.

**Comment by stronnag** [comment]
Range is the maximum straight line distance from home.

I'm going to close this; if these's anything other parameters you think of, please reopen the issue.
