### ISSUE TITLE
bluetooth module hc--06 combatility?

### ISSUE THREAD

**Issue by giogias** [stronnag/mwptools#57]
im making a groundstation and i just install it on raspberry pi 3 b+ using ubuntu Mate
i also have a bluetooth module hc-06 for telemetry with inav telemetry viewer app that works great from this https://github.com/CrazyDude1994/android-taranis-smartport-telemetry
my question is if i have to add external telemetry like 3dr or can i use that bluetooth  module.
i try to connect via bluetooth and change also the baudrate at  9600 that bluetooth uses for communicates and at the MWP i have telemetry working but thats all.

**Comment by stronnag** [comment]
It depends, mainly on the range you require. A BT module will be limited to < 30m which is not really useful. 3DR, HC-12 or LoRA will give much more range. It's often convenient to combine this with BT, e.g.
```
                                                                                                                                                                   
                                                     +----------------+     +-------------------+                                                                  
+--------------------------+                         | Telemtry Radio |     |       Display     |                                                                  
|                          |-----------------------  | and BT Module  |-----|(mwp, ezgiu etc).  |                                                                  
|       Telemtry Radio     |                         |                |     |                   |                                                                  
+--------------------------+                         +----------------+     +-------------------+                                                                  
                                                                 Ground Station                                                                                    
      Aircaft                                                                                                                                                      
                                                                                                          

```
There's a better diagram in the [mwp wiki](https://github.com/stronnag/mwptools/wiki/3DR-Troubleshooting), device comparison (LoRA focussed) in the [mwp wiki](https://github.com/stronnag/mwptools/wiki/Using-LoRa-for-iNav-Telemetry) and copious detail in the [iNav wiki](https://github.com/iNavFlight/inav/wiki/iNavFlight-Missions)

There's also an article on using Smartport telemetry in the [mwp wiki](https://github.com/stronnag/mwptools/wiki/Using-the-smartport-telemetry-with-MWP), including using a BT device to connect the TX output to the ground station.
