### ISSUE TITLE
Typo: Menubar.ui

### ISSUE THREAD

**Issue by wx4cb** [stronnag/mwptools#59]
Nothing Major, I noticed while doing further testing - I just couldn't figure out how to make a PR to your dev branch

File: https://github.com/stronnag/mwptools/blob/master/mwp/menubar.ui

Line 190: 
`          <attribute name="label">Diection View</attribute>
`
Change to: 
`          <attribute name="label">Direction View</attribute>`

**Comment by wx4cb** [comment]
also, if you want, I can do some "machine translations" too

**Comment by stronnag** [comment]
Thanks for spotting that. Fixed in 775e489
