### ISSUE TITLE
bearing 180 degrees out?

### ISSUE THREAD

**Issue by wx4cb** [stronnag/mwptools#62]
not sure if it's me or if python is doing something weird, but in the PolarChanged signal, it seems the bearing is 180 degrees out

![Screenshot from 2019-07-10 20-38-42](https://user-images.githubusercontent.com/1495297/61013910-ca687580-a352-11e9-8dce-fb94faae3e5e.png)

**Comment by stronnag** [comment]
I recall we already discussed this https://github.com/stronnag/mwptools/issues/56#issuecomment-494688791
A legacy artefact with a (g)setting to reverse it in the UI (see link).
The DBus message is from home to the aircraft regardless https://github.com/stronnag/mwptools/wiki/mwp-Dbus-API#getpolarcoordinates

**Comment by wx4cb** [comment]
i couldn't remember whether we did or not. it's been a crazy week
