### ISSUE TITLE
can't compile - glib.h

### ISSUE THREAD

**Issue by wx4cb** [stronnag/mwptools#63]
weird issue, fresh SD card in my rPI3 using ubuntu mate as the os.

it complains that glib.h can't be found yet iknow obviously gtk and glib are installed. I tried just a blank test program and same thing.

Any thoughts?

```
charlesb@GroundStation:~$ cat > demo.c
#include <glib.h>

void main(void) {
}
charlesb@GroundStation:~$ cc demo.c
tst.c:1:10: fatal error: glib.h: No such file or directory
 #include <glib.h>
          ^~~~~~~~
compilation terminated.
charlesb@GroundStation:~$ locate glib.h
/snap/core/7275/usr/include/reglib/reglib.h
/snap/core/7399/usr/include/reglib/reglib.h
/usr/include/dbus-1.0/dbus/dbus-glib.h
/usr/include/glib-2.0/glib.h
/usr/include/harfbuzz/hb-glib.h
/usr/include/json-glib-1.0/json-glib/json-glib.h
/usr/include/reglib/reglib.h

```

yet if i compile it like this, it works

`gcc -o demo $(pkg-config --cflags glib-2.0 dbus-glib-1) demo.c $(pkg-config --libs glib-2.0 dbus-glib-1)
`

**Comment by stronnag** [comment]
> yet if i compile it like this, it works
> 
> `gcc -o demo $(pkg-config --cflags glib-2.0 dbus-glib-1) demo.c $(pkg-config --libs glib-2.0 dbus-glib-1)`

It's because `glib.h` is in a sub-directory of `/usr/include` and not on the default include search path.
`pkg-config` supplies the correct include search path, and should always be used to build glib and gtk programs.

```
$ pkg-config --cflags glib-2.0
-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include 

```

**Comment by wx4cb** [comment]
so how do i put this in the make file for mwptools ?

**Comment by stronnag** [comment]
On August 16, 2019 8:55:06 AM UTC, wx4cb <notifications@github.com> wrote:
>so how do i put this in the make file for mwptools ?
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/stronnag/mwptools/issues/63#issuecomment-521938904

Try `make clean all` first

**Comment by stronnag** [comment]
Closing this on the basis that it's resolved.
