### ISSUE TITLE
Can't insert waypoints using mouse?

### ISSUE THREAD

**Issue by jimpriest** [stronnag/mwptools#64]
On Ubuntu 18.  Just updated to latest via git pull, make, install.

mwp opens but I can't install any points using the mouse?

I can open the tote and 'insert' a point, then move it around the map but I used to be able to doubleclick the map and insert a WP?

**Comment by jimpriest** [comment]
Nevermind - gotta hit the pencil icon - doh!

**Comment by stronnag** [comment]
The default was changed a while ago because it was too easy to mess up using a track pad especially with cold fingers in the field.

You can restore the old behaviour via a setting:
```
gsettings set org.mwptools.planner auto-wp-edit true
```
