### ISSUE TITLE
Setting baud rate

### ISSUE THREAD

**Issue by Jacky2k** [stronnag/mwptools#70]
Hi,
just started using mwp, but I am unable to connect to by drone, as I cannot set the baud rate in mwp. Did I missed something or is that not possible? Why is that not possible? I have a radio link to the drone which is only 9600 baud to get greater range.

**Comment by stronnag** [comment]
I'm sure it's in the manual .... page 3 for example, e.g
```
/dev/ttyUSB0@9600
```
