### ISSUE TITLE
(Question) CLI Map Preseed

### ISSUE THREAD

**Issue by wx4cb** [stronnag/mwptools#75]
Is there any way to pre-seed (say) an OSM mapnik map for a given lat/long bounding box? or maybe x radius around a point from the CLI ?

couldn't find anything in the wiki

**Comment by stronnag** [comment]
Edit => Seed Current Map

**Comment by wx4cb** [comment]
i know that in the actual window. but im talking directly from the CLI

**Comment by stronnag** [comment]
`mwptools/samples/map_seeder.rb`

**Comment by wx4cb** [comment]
great

**Comment by stronnag** [comment]
next you'll ask me how that works, so I'll try and preempt that.
```
$ Projects/mwptools/samples/map_seeder.rb  --help
map_seeder.rb [options]
    -l, --upper-left=LATLON
    -r, --lower-right=LATLON
    -m, --mission-file=FILE
    -u, --uri=URI
    -i, --id=ID
    -z, --zoom=ZOOMS
    -?, --help                       Show this message
```
define the area with -l, -r or by a mission file. `id` is the map cache name (see `~/.cache/champlain/`
URI is the base URI of the online provider, `-z` is a list of the zoom levels.

Even I think it's easily to use the UI in this case.

**Comment by wx4cb** [comment]
no i actually figured that out on my own heh

**Comment by stronnag** [comment]
Hoisted by my own petard, I even documented it 
`samples/map-cache-readme`

for osm-mapnik `https://tile.openstreetmap.org/#Z#/#X#/#Y#.png`

It might even work after all these years.
