### ISSUE TITLE
with Smart Port connection , GPS getting wrong Longitude value only but Latitude showing a correct one

### ISSUE THREAD

**Issue by gavinlowk** [stronnag/mwptools#83]
Hi All,
with the same configuration , the GPS ( NEO-7N ) value does not have any problem of showing on 
 CrazyDude1994 / android-taranis-smartport-telemetry .

Does anyone have an idea ?

Thanks

**Comment by stronnag** [comment]
Cannot reproduce. Please capture the serial stream and make it available if you'd like me to take look.

**Comment by stronnag** [comment]
closing (no further information)
