### ISSUE TITLE
makefile  error for otxlog

### ISSUE THREAD

**Issue by wx4cb** [stronnag/mwptools#88]
a manual make in the otxlog directory works fine so not a compilation issue in that sense

```
make -C otxlog local
cat docs/warn-local.txt
make[1]: Entering directory '/usr/src/RC/stronnag/mwptools/otxlog'
make[1]: *** No rule to make target 'local'.  Stop.
make[1]: Leaving directory '/usr/src/RC/stronnag/mwptools/otxlog'
make: *** [Makefile:23: local-otxlog] Error 2

```
same for a make local install

**Comment by stronnag** [comment]
fixed in development 844a37b

Thanks for reminding me to remove the aberration that is `make local` in the near future.

**Comment by wx4cb** [comment]
i dunno... i like make local.... :D

**Comment by stronnag** [comment]
It's gone

**Comment by stronnag** [comment]
Oh no it hasn't. On reflection, I reverted the commit.
