### ISSUE TITLE
compiling error: valac: command not found

### ISSUE THREAD

**Issue by Pitichinaccio** [stronnag/mwptools#89]
Hello,

I tried to install mwptools on Ubuntu 14.04 (unfortunately I don't have a newer one).

Compiling does not work and reports the error: "valac: command not found"  
(could be slightly different in english as my Ubuntu is in german)

The last libvala version (under Ubunto 14) seems to be 0.22. So, maybe that is the reason why it's not working?

best regards,
Bernd

**Comment by Pitichinaccio** [comment]
meanwhile I installed valac-0.22 manually but I still get an error:
"vala toolset is obsolete"

**Comment by stronnag** [comment]
Please see the project README. mwp requires the latest LTS or release.
14.04 is way too old.
