### ISSUE TITLE
Feature Request: Add current and mAh to battery monitor

### ISSUE THREAD

**Issue by wx4cb** [stronnag/mwptools#93]
is it possible to add the current draw and possibly the amount consumed to the battery monitor?

**Comment by wx4cb** [comment]
could it be that i have the window too small maybe? I thought it was in there, just didnt see it... the two logs in the other "issue" are both on inav 3 and i did notice there was a few crc fails, but that could also be the crossfire :D 

never thought to do a log when it was directly connected

**Comment by wx4cb** [comment]
dammit wrong button

**Comment by wx4cb** [comment]
yea i see it in the bblog i'm playing

**Comment by stronnag** [comment]
Thanks for checking. Neither issue is surprising; Mavlink has not been used much since LTM was introduced --- until CRSF came along.

**Comment by stronnag** [comment]
Should be fixed in c47eb75, please check and close if so.

**Comment by wx4cb** [comment]
yup works great....
