### ISSUE TITLE
COM port not working in cygwin

### ISSUE THREAD

**Issue by Pitichinaccio** [stronnag/mwptools#94]
Hello Jonathan,

when I open mwp the list of available devices is empty. 

I can connect to my FC via the INAV configurator and it shows that it's on COM9 @57600 baud.

So I just typed "/dev/ttyS8@57600" into the device field and click connect, but nothing happens.
I can't upload a mission, so it seems that there still is no connection. 

If I type e.g. "/dev/ttyS7" or any other number there comes an error message. 

Bernd

**Comment by stronnag** [comment]
1. The list of devices will always be empty; cygwin does not support the Linux device enumeration.
2. On Win10, `/dev/ttyS2@57600` works (in a VM with USB passthrough). OTOH, it's a VCP FC so baud rate is somewhat meaning less.
3.  I have no idea whether why this would not work on Wn7.
