### ISSUE TITLE
Program 'go' not found

### ISSUE THREAD

**Issue by Thidsa** [stronnag/mwptools#96]
fishman@y700:~/Projects/mwptools$ meson build --prefix=/usr  --buildtype=release --strip
The Meson build system
Version: 0.56.2
Source dir: /home/fishman/Projects/mwptools
Build dir: /home/fishman/Projects/mwptools/build
Build type: native build
Project name: mwptools
Project version: 4.182.463
C compiler for the host machine: cc (gcc 10.3.0 "cc (Ubuntu 10.3.0-1ubuntu1) 10.3.0")
C linker for the host machine: cc ld.bfd 2.36.1
Vala compiler for the host machine: valac (valac 0.48.17)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program meson/post_install.sh found: YES (/home/fishman/Projects/mwptools/meson/post_install.sh)
Configuring mwp-config.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gudev-1.0 found: YES 234
Run-time dependency ncurses found: YES 6.2.20201114
Library m found: YES
Program go found: NO

meson/meson.build:57:0: ERROR: Program 'go' not found

**Comment by stronnag** [comment]
Installation documentation updated in b17560b
`sudo apt install golang-go`
